heat_template_version: 2015-04-30

resources:
  compute_instance:
    type: OS::Nova::Server
    properties:
      flavor: 1 GB General Purpose v1
      image: c656f3c8-12ff-4b2e-9333-9a857c553292
      name: Single Server Stack

outputs:
  public_ip:
    description: public IP address of the deployed compute instance
    value: { get_attr: [compute_instance, accessIPv4] }
