heat_template_version: 2014-10-16

description: |
  Create a single gluster server with an attached brick.

parameters:

  image:
    type: string
    label: Image name or ID
    description: Server image id to use
    default: CentOS 7 (PVHVM) (Orchestration)

  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: 1 GB General Purpose v1

  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: my_key

  name:
    type: string
    label: server name
    description: hostname of the server
    default: n%index%c%index%

resources:

  gluster_brick:
    type: OS::Cinder::Volume
    properties:
      size: 75

  gluster_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      user_data_format: RAW
      user_data: |
            #!/bin/bash -x
            # Enable EPEL for dependencvies
            yum -y install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            # setup Gluster SIG repo
            yum -y install centos-release-gluster38
            # install gluster, samba
            yum -y install glusterfs-server samba
            # enable service
            systemctl enable glusterd.service
            # start service
            systemctl start glusterd.service
            # add open up ports on firewall
            firewall-cmd --zone=public --add-port=24007-24008/tcp --permanent
            # reload firewall rules
            firewall-cmd --reload

  volume_attachment_server1_brick1:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: gluster_brick }
      instance_uuid: { get_resource: gluster_server }
      mountpoint: /dev/xvdc

outputs:
  server_ip:
    value:
      get_attr: [gluster_server, accessIPv4]
