heat_template_version: 2015-10-15

description: |
  Install GlusterFS on a single CentOS7 server with an attached volume

parameters:

  image:
    type: string
    label: Image name or ID
    description: Server image id to use
    default: CentOS 7 (PVHVM) (Orchestration)

  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: 1 GB General Purpose v1

  name:
    type: string
    label: server name
    description: hostname of the server
    default: node

  key_name:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance
    default: my_key

  volume_size:
    type: number
    description: Size of the cloud block storage device (brick) to be created
    default: 75
    constraints:
    - range:
        min: 75
        max: 1024
      description: must be between 75 and 1024 GB.

  cbs_mount_point:
    type: string
    label: cbs mount point
    description: The location where the volume is exposed on the instance
    default: /dev/xvdc

resources:

  gluster_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      name: { get_param: name }

  gluster_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      user_data_format: SOFTWARE_CONFIG
      # POLL_TEMP_URL is only value supported by Rackspace Cloud
      software_config_transport: POLL_TEMP_URL

  volume_attachment_gluster:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: gluster_volume }
      instance_uuid: { get_resource: gluster_server }
      mountpoint: { get_param: cbs_mount_point }

## SoftwareConfig Section

  update_system_config:
    type: OS::Heat::SoftwareConfig
    depends_on: [ gluster_server ]
    properties:
      group: script
      config: |
        #!/bin/bash
        logger "$0: Updating System..."
        yum update -y
        logger "$0: System Update Complete..."

  gluster_service_config:
    type: OS::Heat::SoftwareConfig
    depends_on: [ gluster_server ]
    properties:
      group: script
      config: |
        #!/bin/bash
        logger "$0: Installing Gluster..."
        # install extras
        yum install -y bash-completion-extras ansible
        # setup Gluster SIG repo
        # https://wiki.centos.org/SpecialInterestGroup/Storage
        yum -y install centos-release-gluster310
        # install gluster-server
        yum -y install glusterfs-server
        # enable service
        systemctl enable glusterd.service
        # start service
        systemctl start glusterd.service
        # add open up ports on firewall
        firewall-cmd --zone=public --add-service=glusterfs --permanent
        # reload firewall rules
        firewall-cmd --reload
        # Install native client
        yum install -y glusterfs glusterfs-fuse
        # Install gdeploy
        yum install -y gdeploy
        logger "$0: Gluster Installation Complete..."

  gluster_volume_config:
    type: OS::Heat::SoftwareConfig
    depends_on: [ gluster_server ]
    properties:
      group: script
      inputs:
      - name: node-name
        default: { get_param: name }
      config: |
        #!/bin/bash
        logger "$0: Configuring Gluster Volume..."
        parted -s /dev/xvdc mktable gpt
        parted -s /dev/xvdc mkpart primary 2048s 20%
        parted -s /dev/xvdc set 1 lvm on
        pvcreate /dev/xvdc1
        vgcreate vg_bricks /dev/xvdc1
        lvcreate -l 100%FREE -T vg_bricks/thinpool
        for i in 1 2 3 4; do
          lvcreate -V 2G -T vg_bricks/thinpool -n node-name-brick-$i
          mkfs.xfs -i size=512 /dev/vg_bricks/node-name-brick-$i
          mkdir -p /bricks/brick-$i
          echo "/dev/vg_bricks/node-name-brick-$i /bricks/brick-$i xfs rw,inode64,noatime,nouuid 0 0" >> /etc/fstab
        done
        mount -a
        logger "$0: Gluster Volume Configuration Complete..."


## SoftwareDeployment Section

#  update_system_deploy:
#    type: OS::Heat::SoftwareDeployment
#    depends_on: [ update_system_config, gluster_server ]
#    properties:
#      config:
#        get_resource: update_system_config
#      server:
#        get_resource: gluster_server

  gluster_service_deploy:
    type: OS::Heat::SoftwareDeployment
    depends_on: [ gluster_service_config, gluster_server ]
    properties:
      config:
        get_resource: gluster_service_config
      server:
        get_resource: gluster_server

  gluster_volume_deploy:
    type: OS::Heat::SoftwareDeployment
    depends_on: [ gluster_volume_config, gluster_server ]
    properties:
      config:
        get_resource: gluster_volume_config
      server:
        get_resource: gluster_server
      input_values:
        node-name: { get_param: name }
