heat_template_version: 2015-10-15

description: |
  GlusterFS Practice Lab Template
  Installs glusterfs on multiple CentOS7 servers with attached storage volume

parameters:

  image:
    label: Operating System
    description: Image to be used for server 
    type: string
    default: CentOS 7 (PVHVM) (Orchestration)

  flavor:
    label: Server Size
    description: Type of instance (flavor) to be used on the compute instance
    type: string
    default: 1 GB General Purpose v1

  key:
    label: Key name
    description: Name of key-pair to be installed on the compute instance
    type: string
    default: my_key

  volume_size:
    description: Size of the cloud block storage device (brick) to be created
    type: number
    default: 75
    constraints:
    - range:
        min: 75
        max: 1024
      description: Must be between 75 and 1024 GB

  gluster_count:
    label: Gluster Server Count
    description: Number of gluster server instances to provision
    type: number
    default: 2

resources:

  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: key }
      save_private_key: true

  gluster_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: gluster_count }
      resource_def:
        type: gluster.yaml
        properties:
          image: { get_param: image }
          flavor: { get_param: flavor }
          name: node%index%
          key: { get_resource: ssh_key } 
          pubkey: { get_attr: [ssh_key, public_key] }
          privkey: { get_attr: [ssh_key, private_key] }
          volume_size:  { get_param: volume_size }
          index: '%index%'

outputs:

  private_key:
    description: Private key
    value: { get_attr: [ssh_key, private_key] }
