heat_template_version: 2015-10-15

description: |
  GlusterFS Practice Lab Template
  Installs glusterfs on multiple CentOS7 servers with attached storage volume

parameters:

  image:
    type: string
    label: Operating System
    description: Image to be used for server
    default: CentOS 7 (PVHVM) (Orchestration)

  flavor:
    type: string
    label: Server Size
    description: Type of instance (flavor) to be used on the compute instance
    default: 1 GB General Purpose v1

  key_name:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance
    default: my_key

  volume_size:
    type: number
    description: Size of the cloud block storage device to be created
    default: 75
    constraints:
    - range:
        min: 75
        max: 1024
      description: Must be between 75 and 1024 GB

  gluster_count:
    type: number
    label: Gluster Server Count
    description: Number of gluster server instances to provision
    default: 2

resources:

  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: key_name }
      save_private_key: true

  export_hosts:
    type: OS::Heat::SoftwareConfig
    properties:
      outputs:
        - name: hosts
      group: script
      config: |
        #!/bin/sh
        (echo -n $(facter ipaddress); echo -n ' '; echo $(facter hostname)) > ${heat_outputs_path}.hosts

  export_hosts_sdg:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: export_hosts }
      servers: { get_attr: [gluster_nodes, refs_map] }
      signal_transport: TEMP_URL_SIGNAL

  populate_hosts:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: hosts
      group: script
      config: |
        #!/usr/bin/env python
        import ast
        import os
        import string
        import subprocess
        hosts = os.getenv('hosts')
        if hosts is not None:
            hosts = ast.literal_eval(string.replace(hosts, '\n', '\\n'))
        with open('/etc/hosts', 'a') as hosts_file:
          for ip_host in hosts.values():
              hosts_file.write(ip_host.rstrip() + '\n')

  populate_hosts_sdg:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: export_hosts_sdg
    properties:
      config: { get_resource: populate_hosts }
      servers: { get_attr: [gluster_nodes, refs_map] }
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        hosts: { get_attr: [ export_hosts_sdg, hosts ] }


  gluster_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: gluster_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          image: { get_param: image }
          flavor: { get_param: flavor }
          name: n%index%
          key_name: { get_resource: ssh_key }
          user_data_format: SOFTWARE_CONFIG
          # POLL_TEMP_URL is only value supported by Rackspace Cloud
          software_config_transport: POLL_TEMP_URL

outputs:

  private_key:
    description: Private key
    value: { get_attr: [ssh_key, private_key] }
