heat_template_version: 2015-10-15

description: |
  GlusterFS Practice Lab Template
  Installs glusterfs on multiple CentOS7 servers with attached storage volume
  Depends upon gluster.yaml to run

parameters:

  image:
    type: string
    label: Operating System
    description: Image to be used for server
    default: CentOS 7 (PVHVM) (Orchestration)

  flavor:
    type: string
    label: Server Size
    description: Type of instance (flavor) to be used on the compute instance
    default: 1 GB General Purpose v1

  key_name:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance
    default: my_key

  volume_size:
    type: number
    description: Size of the cloud block storage device to be created
    default: 75
    constraints:
    - range:
        min: 75
        max: 1024
      description: Must be between 75 and 1024 GB

  gluster_count:
    type: number
    label: Gluster Server Count
    description: Number of gluster server instances to provision
    default: 2

resources:

  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: key_name }
      save_private_key: true

  gluster_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: gluster_count }
      resource_def:
        type: gluster.yaml
        properties:
          image: { get_param: image }
          flavor: { get_param: flavor }
          name: n%index%
          key_name: { get_resource: ssh_key }

outputs:

  private_key:
    description: Private key
    value: { get_attr: [ssh_key, private_key] }
