heat_template_version: 2015-04-30

description: Template that installs multiple gluster servers, brinks.

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. 
    default: CentOS 7 (PVHVM) (Orchestration)
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: 1 GB General Purpose v1
  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: my_key

resources:
  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: key }
      save_private_key: true
  multi-gluster:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: gluster.yaml
        properties:
          image: { get_param: image }
          flavor: { get_param: flavor }
          name: n%index%c%index%
          key: { get_resource: ssh_key } 
outputs:
  private_key:
    description: Private key
    value: { get_attr: [ssh_key, private_key] }
