heat_template_version: 2014-10-16

description: |
  Create a single gluster server with an attached volume.

resources:

  # This key pair must already exist
  existing_key_pair:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Nova::KeyPair
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: public_key_name }
      public_key:  { get_param: public_key_value }

  gluster_brick:
    type: OS::Cinder::Volume
    properties:
      size: 75

  gluster_server:
    type: OS::Nova::Server
    properties:
      name: n-%index%
      flavor: 1 GB General Purpose v1
      image: CentOS 7 (PVHVM) (Orchestration)
      user_data_format: RAW
      user_data: |
            #!/bin/bash -x
            # Enable EPEL for dependencvies
            yum -y install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            # setup Gluster SIG repo
            yum -y install centos-release-gluster38
            # install gluster, samba
            yum -y install glusterfs-server samba
            # enable service
            systemctl enable glusterd.service
            # start service
            systemctl start glusterd.service
            # add open up ports on firewall
            firewall-cmd --zone=public --add-port=24007-24008/tcp --permanent
            # reload firewall rules
            firewall-cmd --reload

  volume_attachment_server1_brick1:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: gluster_brick }
      instance_uuid: { get_resource: gluster_server }
      mountpoint: /dev/xvdc

outputs:
  server_ip:
    value:
      get_attr: [gluster_server, accessIPv4]
